package com.example.clothapp.repository;

import com.example.clothapp.model.ClothingItem;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

@JdbcTest
@Import(JdbcClothingItemRepository.class)
class JdbcClothingItemRepositoryTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private JdbcClothingItemRepository repository;

    @BeforeEach
    void setUp() {
        // Recreate schema for each test to be independent of application SQL init
        jdbcTemplate.execute("DROP TABLE IF EXISTS clothing_item");
        jdbcTemplate.execute("CREATE TABLE clothing_item (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "name VARCHAR(255) NOT NULL," +
                "size VARCHAR(50) NOT NULL," +
                "color VARCHAR(50) NOT NULL," +
                "price DOUBLE NOT NULL," +
                "stock INT NOT NULL," +
                "category VARCHAR(100))");
    }

    @Test
    void save_newItem_shouldInsertAndReturnWithId() {
        ClothingItem item = new ClothingItem(null, "Test Shirt", "L", "Red", BigDecimal.valueOf(25.00), 10, "Tops");

        ClothingItem saved = repository.save(item);

        assertNotNull(saved.getId());
        assertEquals("Test Shirt", saved.getName());
    }

    @Test
    void save_existingItem_shouldUpdate() {
        ClothingItem item = new ClothingItem(null, "Original", "M", "Blue", BigDecimal.valueOf(20.00), 15, "Tops");
        ClothingItem saved = repository.save(item);

        saved.setName("Updated");
        saved.setPrice(BigDecimal.valueOf(30.00));
        repository.save(saved);

        Optional<ClothingItem> found = repository.findById(saved.getId());
        assertTrue(found.isPresent());
        assertEquals("Updated", found.get().getName());
        assertEquals(0, found.get().getPrice().compareTo(BigDecimal.valueOf(30.00)));
    }

    @Test
    void findAll_shouldReturnAllItemsOrderedByName() {
        repository.save(new ClothingItem(null, "Zebra Shirt", "M", "White", BigDecimal.valueOf(20.00), 10, "Tops"));
        repository.save(new ClothingItem(null, "Alpha Shirt", "L", "Black", BigDecimal.valueOf(25.00), 5, "Tops"));

        List<ClothingItem> items = repository.findAll();

        assertEquals(2, items.size());
        assertEquals("Alpha Shirt", items.get(0).getName());
        assertEquals("Zebra Shirt", items.get(1).getName());
    }

    @Test
    void findById_whenExists_shouldReturnItem() {
        ClothingItem item = new ClothingItem(null, "Find Me", "S", "Green", BigDecimal.valueOf(15.00), 20, "Tops");
        ClothingItem saved = repository.save(item);

        Optional<ClothingItem> found = repository.findById(saved.getId());

        assertTrue(found.isPresent());
        assertEquals("Find Me", found.get().getName());
    }

    @Test
    void findById_whenNotExists_shouldReturnEmpty() {
        Optional<ClothingItem> found = repository.findById(9999L);

        assertFalse(found.isPresent());
    }

    @Test
    void searchByNameOrCategory_shouldReturnMatchingItems() {
        repository.save(new ClothingItem(null, "Red Shirt", "M", "Red", BigDecimal.valueOf(20.00), 10, "Tops"));
        repository.save(new ClothingItem(null, "Blue Jeans", "32", "Blue", BigDecimal.valueOf(50.00), 8, "Bottoms"));
        repository.save(new ClothingItem(null, "Red Pants", "L", "Red", BigDecimal.valueOf(40.00), 5, "Bottoms"));

        List<ClothingItem> results = repository.searchByNameOrCategory("red");

        assertEquals(2, results.size());
        assertTrue(results.stream().anyMatch(i -> i.getName().equals("Red Shirt")));
        assertTrue(results.stream().anyMatch(i -> i.getName().equals("Red Pants")));
    }

    @Test
    void deleteById_shouldRemoveItem() {
        ClothingItem item = new ClothingItem(null, "Delete Me", "M", "Gray", BigDecimal.valueOf(30.00), 12, "Tops");
        ClothingItem saved = repository.save(item);

        repository.deleteById(saved.getId());

        Optional<ClothingItem> found = repository.findById(saved.getId());
        assertFalse(found.isPresent());
    }
}
